### ISSUE TITLE
Doesnt work with node js wrapper?

### ISSUE THREAD

**Issue by c3budiman** [Surnet/docker-wkhtmltopdf#40]
hi love your works, but i kinda stressed out why it is not working on my projects. 
i use this wrapper: https://www.npmjs.com/package/wkhtmltopdf
and run it in windows server 2019 environment, with docker. 

minimal replication:
```ts
// tes.js
var fs = require("fs");
var wkhtmltopdf = require('wkhtmltopdf');

// URL
wkhtmltopdf('http://google.com/', { pageSize: 'letter' })
  .pipe(fs.createWriteStream('out.pdf'));
```

my dockerfile:
```dockerfile
FROM surnet/alpine-node-wkhtmltopdf:16.18.0-0.12.6-full AS deps

ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /app && cp -a /tmp/node_modules /app/

# Set work directory
WORKDIR /app
COPY . /app

RUN npx prisma generate
# RUN npm run swagger
# RUN npm run build

COPY ./templates /app/dist/templates

# Set the command to run your app
CMD ["npm", "run", "dev"]
```

my compose:
```yml
version: "3.1"

services:
  backend:
    build: "./"
    image: ppic-pil:latest
    container_name: api-ppic
    hostname: apippic
    command: sh -c "env | grep -E '^[A-Za-z_]+=' > .env && npm run dev"
    volumes:
      - "./photo:/app/photo"
      - "./pdf:/app/pdf"
      - "./signature:/app/signature"
    ports:
      - target: 9334
        published: 9334
        protocol: tcp
    env_file:
      - ./.env
    restart: always
```

but it return weird error and no way i could possibly know why? when i run node test.js or my project function. it is working well on native machine running ubuntu, mac, and windows but cant work properly on docker running alpine and debian. any ideas?

![image](https://github.com/Surnet/docker-wkhtmltopdf/assets/1578830/cafc5822-d44b-43b7-8a0b-d26d3dd0107e)
